---
- !arl.amrita.edu,2006/route
  name: EKM to TVM
  nodes:
            -
              seq:  1
              name: EKM
              tt:   0
              code: T005
            -
              seq:  2
              name: ALP
              tt:   55
              code: T004
            -
              seq:  3
              name: KYM
              tt:   50
              code: T003
            -
              seq:  4
              name: KLM
              tt:   55
              code: T002
            -
              seq:  5
              name: TVM
              tt:   90
              code: T001
  vehicles:
            -
              code: V005
              lic:  KL2-3345
              tod:  10

- !arl.amrita.edu,2006/route
  name: TVM to ALP
  nodes:
            -
              seq:  1
              name: TVM
              tt:   0
              code: T001
            -
              seq:  2
              name: KLM
              tt:   90
              code: T002
            -
              seq:  3
              name: KYM
              tt:   55
              code: T003
            -
              seq:  4
              name: ALP
              tt:   50
              code: T004
  vehicles:
            -
              code: V003
              lic:  KL3-5395
              tod:  10
            -
              code: V004
              lic:  KL2-9448
              tod:  25

- !arl.amrita.edu,2006/route
  name: KYM to ALP
  nodes:
            -
              seq:  1
              name: KYM
              tt:   0
              code: T003
            -
              seq:  2
              name: ALP
              tt:   50
              code: T004
  vehicles:
            -
              code: V002
              lic:  KL9-3041
              tod:  10
            -
              code: V001
              lic:  KL8-5692
              tod:  25

